#!/bin/bash
# This script implements the pipelie of nxml2txt

# if [ "$#" -eq 1 ]; then
#   echo "Processes an nxml file and generates the FRIES format"
#   echo "Usage: $0 [--no-citations] arg1 ... argN"
# fi

flags="--no-header"

if [ $1 == "--no-citations" ]; then
  echo "Removing citations"
  flags="$flags --no-citations"
  shift
fi

for FILE in $@; do
  echo "Working on $FILE"
  NAME=${FILE%.*} # Remove the extension of the nxml file

  # Call nxml2txt
  nxml2txt $FILE $NAME.txt $NAME.so
  # Call nxml2fries
  python $(dirname $0)/nxml2fries.py $flags  $NAME.txt $NAME.so > ${NAME}.tsv
done
